### ISSUE TITLE
Unable to send image

### ISSUE THREAD

**Issue by apothis** [hyperion-project/hyperion.kodi#33]
Been using this for a while on kodi (various versions, latterly 16.1) running on ubuntu with no problems. For various reasons, I've rebuilt that box to libreelec (latest beta, with kodi 17 beta) on it. Just reinstalled this addon, and its not working. when starting playback, I get a quick flash from the LEDs as if its going to work, then nothing. After a little while, I get a popup saying unable to send image to hyperion.

Hyperion is running remotely on a pi, nothing has changed there, not had issues previously

Nothing I can see in the kodi log either

**Comment by ninovanhooff** [comment]
I was also using hyperion on rpi2 + kodi 16 on Android for a very long time without problems. But after an upgrade to official Kodi 17 it stopped working.

What worked for me to fix it:
- update hyperion to the latest version (as a result the hyperiond service was restarted)
- update kodi plugin to the latest (1.0.2)
- In Kodi Settings > Player Settings, disable Allow Hardware Acceleration - MediaCodec (Surface) (might only be needed on Android)
- in plugin settings, set priority to a low value (meaning high priority) Try to find the highest value that still works, eg 1, 7 and 60 worked, but 100 did not work, so I put it at 60)
- Done!

restarting hyperion might be important because we know for sure that no device is trying to set the lights to black, since all connections will be broken
Setting priority to a low value is important so the chance that kodi is overruled is minimized

Hopes this works for you as well!

If this is a solution but your system is not powerful enough to play videos without hardware acceleration and you are running Kodi on Android, I've heard SPMC fork of Kodi supports the hyperion  plugin with acceleration enabled. Just download it from the play Store! ( it's Kodi 16, still)

**Comment by milhouse34521** [comment]
I am having the same issue, but running Kodi 17 on Windows. I can control Hyperion (latest version - installed today) with the Hyperion Android App, running on a new install on a Raspberry Pi, so I know its working. But I get the same error when using the Hyperlink Ambilight plugin (1.0.2).  Is it possible to create a log on the kodi side?
