### ISSUE TITLE
Kodi addon Flickering on Linux (Debian / Ubuntu)

### ISSUE THREAD

**Issue by Satyriconhu** [hyperion-project/hyperion.kodi#44]
Hi. 

I noticed that on Linux some linux distors (POP_OS!, and LMDE), the kodi addon is misbehaving, but on windows it's working fine.

**The symptom:**
Generally flashing/flickering lights with every refresh. What I've noticed is that during the flashing, it is not not the same colour, it is from the colour palate that was sent. (could try making a video of it)

**Trouble shooting**
- I tried using different version of the addon pulled from github, also older from the my local repo. 
- Resetting the addon settings
- tried different capture properties, and refresh rates
- pulling the addons directly from my windows install 
- refreshing the hyperion server

**Thoughts**
Before I installed Pop_OS, i used its live version, Installed kodi, with the addon, there it was working fine. So my assassination is that either kodi's image capture, or the addon has issues with Cinnamon, or the Gnome desktop environment. 

I tried to install Hyperion.ng too to get the X11 grabber working, but as the server and the host are not the same, I had difficulty getting it connected.

**Software info**
Kodi 18.5 on Windows 18.6 on POP_OS and 1.0.2 Plugin, and latest hyperion server via hypercon.

_**PS**
I'll try and get some time to upload a brief video of the symptom, and maybe upload the captured image data sent by the addon both from windows, and linux._

**Maybe related**
https://github.com/hyperion-project/hyperion.kodi/issues/40

**Comment by Satyriconhu** [comment]
Update: Seems to be an issue with resolution. @4k it happens, at FHD, it's fine. (Setting the grabber resolution wont affect it) both cases are on default

**Comment by cmsimike** [comment]
Hello,

I setup this plugin and noticed the same sort of flickering, but on 1080p content. I've been able to trace it to kodi playing content > 30fps. I have a few videos that are 30fps and lower, and hyperion + this plugin work perfectly. Once it goes above 30fps (tried 48 fps and 60 fps) I get flickering lights.

**Comment by bachulator** [comment]
Seeing same problem. Can we expect fix on the issue. Do we have a workaround?

**Comment by cmsimike** [comment]
@bachulator 
I looked into this problem myself and from what I found, the short answer is that I wouldn't expect a fix for this. It's not really a bug but just two competing systems working against each other with no great current solution.
Kodi is doing the rendering and python is running outside of the context of the render loop. When the plugin asks kodi for a screen shot, at least from what I noticed, the screen shot might be in the middle of another render so you'd get bad data (which then is rendered with the lights).

The solution was to move away from hyperion and start using hyperion.ng. The new version installs directly on the machine running kodi for me and reads from X11 directly rather than kodi. The kodi plugin then really just controls when the lights should be on/off rather than pulling the image.

You might be able to achieve something similar with the old hyperion version but once i saw that there was a new one out, i just threw all my eggs into that basket. Things have been working well since.

**Comment by bachulator** [comment]
Thanks for detailed description @cmsimike. To start from something, I have to explain my current setup. Both kodi and hyperion in my setup are running in separate docker containers. So to be frank I don't fell migration to hyperion.ng will solve the problem. On the other hand pre 18.0 kodi this addon worked rather well so I wonder what change broke the addon. Another rather interesting observation while playing video and restart the hyperion platform the flickering artifacts will disappear, so it feels more like synchronization issue to me. But I get the picture, seems developores are mostly invested to NG nowadays and we hardly can expect any improvements.

**Comment by Paulchen-Panther** [comment]
Sollten sich Hyperion Python Entwickler finden, werde ich sie auf dieses Problem hinweisen.

**Comment by bachulator** [comment]
Thanks @Paulchen-Panther. That would be pretty cool if the problem could be resolved.

**Comment by Kl0use** [comment]
For me the flickering is gone by setting in the kodi player options to always adjust FPS.

**Comment by kuba-orlik** [comment]
Related: https://github.com/xbmc/xbmc/issues/15153

**Comment by Lord-Grey** [comment]
@kuba-orlik Thanks for the reference

**Comment by fightforlife** [comment]
In xbmc master branch it is fixed for me on Debian based Linux. https://github.com/xbmc/xbmc/pull/24439

**Comment by kuba-orlik** [comment]
I can confirm the master branch doesn't flicker. Tried on Arch with gbm
