### ISSUE TITLE
Addon on an android XBMC Player doesn't work

### ISSUE THREAD

**Issue by strikegun** [hyperion-project/hyperion.kodi#6]
my hyperion systems runs well on a openelec x64 system.
If I install the addon on a xbmc of a android mediaplayer, it sends no data to the hyperion rpi server.
Is it because of the internal grapper?

thanks

**Comment by ninovanhooff** [comment]
In the hyperion config, you can disable the grabber because that only works on rpi.
I got this working fine on an Android console with tegra soc.
Are you sure the android stick can reach the pi over the network? Please check whether you configured the ip address right in the plugin settings

**Comment by strikegun** [comment]
the hyperion server stays on the rpi, which is connected to the RGB LED. The XBMC Player ist the android device. I had a PC with openelec which runs fine with the hyperion xbmc-addon. But not on the android device with xbmc.

**Comment by ninovanhooff** [comment]
I understand your setup, mine is comparable.
please try to install an ssh app on the android stick and ping the rpi if you can

**Comment by curunoir** [comment]
Hi, I have a similar setup : Hyperion server on a RPI connected to leds and an android tv box running Kodi on the same network. I do think my android device can reach the hyperion server because when I play a movie on the android device the leds light themselves but remain white. Any clue of what it's going on ? I have disabled the frame grabber option in the hyperion config file.

**Comment by curunoir** [comment]
I have installed OpenElec on the same box and I have the same issue. There is no such issue if I use a Windows pc as Xbmc client or if I use Xbmc from the Pi . It's as is the first picture led data is sent to the hyperion server and then nothing else. Please tell me how I can find more information to see what's going on.

**Comment by pigbait** [comment]
Hey guys, I've setup my amlogic S802 android M8 box with openelec with video capture enabled in the build.

( http://freaktab.com/forum/tv-player-support/amlogic-based-tv-players/eny-acemax-em8-square-em6q-etc-devices/491016-openelec-5-0-8-eny-m8-2g-square-with-amcodec-boblightd-support-updated )

I've talked to the developer of this rom and he mentioned that Hyperion would need to add the amcodec hardware acceleration to its code.. not sure if anyone here could maybe look into it.

This is what he said: "At the moment only boblight is supported because boblight has included the hardware amcodec. My build of Openelec has enabled the amcodec to output to /dev/videocap0 so that boblight can pick it up and do its thing.

If this is the official github of hyperion https://github.com/tvdzwan/hyperion you can open an issue and ask for them to add amcodec support. You are better off asking them due to you having all the hardware that is required for hyperion."

**Comment by y0gib3ar** [comment]
My 2 cents,
I have also tried to add this addon on my minix X8-h Plus and found that only SDTV compressed movies will play with the hyperion ambilight on an Raspberry with openelec. 
But when using a HTPC with openelec or a Samsung note 2014 or an Asus memo tablet both with kodi from the google play site, this script works. No problems for 720p and 1080p (have no higher coded movies)
Also tried kodi from the google play site on my minix but still no cigar.
Edit:
On Minix the AMcodec is the problem, install SPMC (or another XBMC fork with the hardware options) and disable AMcodec, now you only get software decoding, Ambilight with hyperion works now but because the TV box has to work harder, some video/audio syncing occurs.

**Comment by brindosch** [comment]
There is just support for not special hardware accelerated clients atm. We will see what we could do.
